### ISSUE TITLE
the doc partof #js_compare  is wrong, it lost context

### ISSUE THREAD

**Issue by vtejuf** [nolimits4web/Template7#10]
in doc #js_compare  be used like :
<p>{{#js_compare "a === b"}}A equals to B{{else}}A not equal to B{{/js_compare}} </p>

i use #js_compare in a {{#each}} like 
"{{#js_compare "sales == 1"}}1{{else}}2{{/js_compare}}"
but i get error "sales not defined"

the sales lost it context . in right way like
"{{#js_compare "this.sales == 1"}}1{{else}}2{{/js_compare}}"

**Comment by nolimits4web** [comment]
There is a box in docs saying:
> Nore that in js and in js_compare helper you may need to use this.variableName instead of just variableName
