### ISSUE TITLE
really cool ! but can you let it fly to the sky?

### ISSUE THREAD

**Issue by jacobking** [nolimits4web/Template7#18]
if i can put a url target of  template page when i use myApp.router.load({template:'templage/list.html',content:{first:'fly',last:'sky'}}),that will be awesome! @nolimits4web

**Comment by jacobking** [comment]
well,just minuties i think an idea that is just wite the template language to the target page,when i onPageInit of this target page just let it's content be a template,when i compiledTemplate let this result rewrite target page's content.just like this:

```
 geoApp.onPageInit('setting',function(page){
	var template = $$('#setting-list').html();
	 
	var compiledTemplate = Template7.compile(template);
	 
	var context={
		firstName: 'Jacob',
	    lastName: 'King'
	};
	var html = compiledTemplate(context);
	$$('#setting-list').html(html);
})

```

**Comment by nolimits4web** [comment]
You can also do it like:
```js
$.get('template/list.html', function(template){
  myApp.router.load({template:template,context:{first:'fly',last:'sky'}})
});
