### ISSUE TITLE
Format variables

### ISSUE THREAD

**Issue by KLVN** [nolimits4web/Template7#2]
Hey,
is it possible to format variables before they get rendered? I want to convert "pubDate" in RSS Feeds into DAY. MONTH YEAR (e.g. 16. January 2015) scheme?

**Comment by KLVN** [comment]
Workaround: I formatted "pubDate" now with Yahoo Pipes and it's working fine now.

**Comment by nolimits4web** [comment]
That is what Helpers are designed for:
```
Template7.registerHelper('formatDat', function(date){
  var newDate = ... //do something here to modify 'date' string
  return newDate;
})
```
And then in template:
```
Date is {{formatDate pubDate}}
