### ISSUE TITLE
Ability to get item by index

### ISSUE THREAD

**Issue by kouts** [nolimits4web/Template7#3]
Great work on Template7, can you add the ability to get item by index e.g:
{{clients.1.name}} or {{clients.[1].name}}
It would be cool if you could. Thanks.

**Comment by nolimits4web** [comment]
Hi, but you already could do it like in your example: {{clients.1.name}}

**Comment by kouts** [comment]
I tried it but it does not work, I get error "SyntaxError: missing ) after argument list"

**Comment by kouts** [comment]
Lets take for example this context:
```
        var pagedata = {
            clients: [{name: 'John'}, {name: 'George'}, {name: 'Nikos'}],
            others: ['John', 'George', 'Nikos'],
            names: 'Giannis'
        };

```
When I try to access {{clients.1.name}} or {{others.1}} it does not work.

**Comment by nolimits4web** [comment]
I was sure that it should work. Thanks, will try to implement it

**Comment by kouts** [comment]
Thanks, I really like Template7 for it's speed and simplicity, adding this would be great, thanks.

**Comment by mewben** [comment]
Hi, I also get this error "SyntaxError: missing ) after argument list" when accessing the array index directly
