### ISSUE TITLE
Templating - respect spaces 

### ISSUE THREAD

**Issue by michapixel** [nolimits4web/Template7#41]
i got an error when compiling e.g.
´´´
{{ emails.all }}
´´´
note the spaces!
by deleting the spaces `{{emails.all}}` i got the correct template/output/no error.
I could live with that but i think the parsing should be more graceful in this case.

**Comment by ZanderBrown** [comment]
What spaces am I supposed to be noting?

**Comment by michapixel** [comment]
inside the curly braces, if you put a space before your variable it throws an error on compiling.

**Comment by ZanderBrown** [comment]
Ah so we are talking `{{ emails.all }` vs `{{emails.all}}` here?

Seems odd that it wouldn't be valid, perhaps @nolimits4web 's parsing is a little too strict here

Side note: @nolimits4web perhaps this repository should be under @framework7io?
