### ISSUE TITLE
Add "defineContextVariable" build in helper

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Template7#43]
Hello @nolimits4web,

could you please add a new build in helper to define context variables.

Thanks :)

**Comment by J05HI** [comment]
@nolimits4web
Could you please have a look at this, it would be an amazing feature :)

**Comment by J05HI** [comment]
@nolimits4web
Could you please have a look at this, it would be an amazing feature :)

**Comment by nolimits4web** [comment]
It is already possible by using `{{#objectName}} .... {{/objectName}}`, e.g.:
```
var obj = {
  foo: 'bar',
};
```
```
{{#obj}}
<p>{{foo}}</p>
{{/obj}}

**Comment by J05HI** [comment]
@nolimits4web 
Great!
Thank you very much!!!
