### ISSUE TITLE
partial helper:  use variable as partial name 

### ISSUE THREAD

**Issue by scramatte** [nolimits4web/template7#46]
Hi,

It would be nice to be able render a partial using a variable as helpernmae.
Currently helper doesn't make difference between  "partialname"  or partialname (without double quotes).  

What I mean  is considering following partials names:
1.  text
2. textarea
3. select
...

And a variable called type that can contains "text", "textarea" or "select"
I would like to be able to achieve the following
{{> type}}

And so  partial helper should resolve properly name.
Regards

**Comment by nolimits4web** [comment]
Add support for dynamic helper names and partials using `[]`:
```js
Template7.registerPartial('input', '<input type="text">');
Template7.registerPartial('textarea', '<textarea></textarea>');
Template7.registerPartial('select', '<select><option>1</option><option>2</option></select>');

var template = `
  {{#each inputs}}
    {{> [type]}}
  {{/each}}
`;

var result = Template7.compile(template)({
  inputs: [
    {
      type: 'input',
    },
    {
      type: 'textarea',
    },
    {
      type: 'select',
    },
  ]
})

console.log(result);
