### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by pavelloz** [nolimits4web/template7#5]
Hi,

Are you at all interested in tests for Template7 or do you think it is not useful to have them?

Im asking because i chose T7 as my learning project for testing in mocha+chai+karma, would you like me to create PR after i finish? Im not saying it will be perfect, but certainly it would be better than nothing.

Regards,
Paweł

**Comment by nolimits4web** [comment]
Hi,

I am not really familiar with all these test frameworks, but i think they could be useful for such lib because it is hard to compile/test many cases of T7 usage with different contexts. So sure, send me PR when it will be ready
