### ISSUE TITLE
how to equal two variables from different contexts?

### ISSUE THREAD

**Issue by lukasMega** [nolimits4web/Template7#6]
My template context object example:
```javascript
{
	label: "Image Size",
	current: "3872x2592",
	choices: [
		"3872x2592",
		"2896x1944",
		"1936x1296"
	]
}
```
my template: 
```html
{{#if choices}}
  <select name="{{label}}">
    {{#each choices}}
    <option value="{{@index}}" {{#js_compare "this == current"}}selected{{/js_compare}} >
      {{this}}
    </option>
    {{/each}}
  </select>
{{/if}}
```
I need compare every item in ```{{#each}}``` block with variable from parent context (in my case variable ```current```)
I tried:
 - current
 - {{../current}}
 - ../current

... no success.
Is it possible?
Thanks for answer :)

**Comment by nolimits4web** [comment]
It is impossible to use js_compare to access parent context, so it is better to create custom helper like:
```js
Template7.registerHelper('isSelected', function (a,b){
  if (a === b) return 'selected';
  else return '';
})
```
And then to use it like:
```html
{{#if choices}}
  <select name="{{label}}">
    {{#each choices}}
    <option value="{{@index}}" {{isSelected this ../current}} >
      {{this}}
    </option>
    {{/each}}
  </select>
{{/if}}

**Comment by lukasMega** [comment]
Thanks for quick answer. It was so simple! :-O

**Comment by MarioVanDenEijnde** [comment]
Hello NoLimits4Web,

We use the template7 in Framework7.
Can you tell me where to register the helper (where to put the code)
Wherever I tried I keep ending up with: Uncaught Error: Template7: Missing helper: 'isSelected'

Kind regards,
Mario
