### ISSUE TITLE
js not working in IOS?

### ISSUE THREAD

**Issue by KyooMario** [nolimits4web/template7#72]
Framework7 version: 5.7.1
Platform and Target: iphone 7 iOS 13.4.1

It seems that the use of js in IOS does not work. On chrome it works fine.
Example: {{js "new Date(this.StartDate).getDate()"}} returns "19" fine on Chrome but NaN in IOS.

Please advise,

Kind regards,
Mario

**Comment by nolimits4web** [comment]
It means that what you have in `this.StartDate` is in wrong or not parseable format by Safari
