### ISSUE TITLE
enhance Template7.registerPartial

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Template7#9]
Would be nice to enhance this method:

- Template7.registerPartial(name, template)

with templateURL

Template7.registerPartial(name, templateURL)

where templateURL is a template.html file, which includes the template.

It is not good maintainable to have html-strings in javascript..

**Comment by nolimits4web** [comment]
There is no includes in JS. Only option is to do Ajax request to maintain it, but it will produce more errors and questions, as it is asynchronous. So you can do it by yourself
